---
title: "Rmd File"
author: "Arielle Dror, Kara Van Allen, Emily Daubenspeck"
date: "November 18, 2018"
output: html_document
---
First Rough Draft

```{r, message = FALSE, warning = FALSE}
library(tidyverse)
library(igraph)
library(readr)
library(sna)
library(ggplot2)
library(mosaic)
library(blockmodels)
library(ergm)
library(intergraph)

bill_sponsers_data <- read_csv("bill_sponsers_data.csv")
length(unique(bill_sponsers_data$bill_number))

bill_sponsers_data <- bill_sponsers_data %>%
  mutate(sponsor = ifelse(position == 1, TRUE, FALSE))

node_characteristics <- read_csv("node_characteristics.csv")
```

```{r creating matrix}
split_name <- str_split_fixed(node_characteristics$Name, " ", 3)
  
node_characteristics <- node_characteristics %>%
  mutate(firstLast = paste(split_name[, 2], split_name[, 1], sep = ' ')) %>%
  mutate(firstLast = gsub(',', replacement = '', firstLast)) %>%
  mutate(firstLast = if_else(firstLast == "Hollen Van", "Chris Van Hollen", firstLast)) %>%
  mutate(firstLast = if_else(firstLast == "Catherine Masto", "Catherine Cortez Masto", firstLast)) %>%
  mutate(weight = (`Number of bills cosponsered` + `Number of bills sponsered`)/3600)

names_people <- c(node_characteristics$firstLast)

short_sponsors <- bill_sponsers_data %>%
  select(bill_number, name)
cosponsors <- c(short_sponsors$name)

cosponsors<-unique(cosponsors)

node_characteristics_temp <- node_characteristics %>%
  select(firstLast, State, Gender, Age, weight)

node_characteristics_temp$firstLast <- node_characteristics_temp$firstLast[order(match(node_characteristics_temp$firstLast,cosponsors))]

node_characteristics_final <- left_join(node_characteristics_temp, node_characteristics, by = "firstLast")
node_characteristics_final <- node_characteristics_final %>%
  select(firstLast, State.y:weight.y) %>%
  rename(State = State.y,
         Age = Age.y,
         Gender = Gender.y,
         Weight = weight.y)


#node_characteristics <- node_characteristics %>%
 #mutate(firstLast = node_characteristics_order)

mat<-diag(105) #check this :)

diag(mat)<-0 

for(n in unique(short_sponsors$bill_number)) {
  short_sponsors_temp <- short_sponsors %>%
   filter(bill_number == n)
   names_people<-short_sponsors_temp$name
 
mat[cosponsors%in%(names_people), cosponsors%in%(names_people)] <- mat[cosponsors%in%(names_people), cosponsors%in%(names_people)] + 1
#end loop
}

diag(mat)<-0


attempt <- function(bill_num){
  filter(short_sponsors$bill_number == bill_num)
  cosponsors <- c(short_sponsors$name)
  mat[cosponsors, cosponsors] <- mat[cosponsors, cosponsors] + 1
}


diag(mat)<-0
  

```


```{r plotting matrix}
set.seed(5)
sponser_matrix_full <- as.matrix(mat)
sponser_matrix <- as.matrix(mat)
upper.tri(sponser_matrix, diag = TRUE)
diag(sponser_matrix) <- NA
sponser_matrix[upper.tri(sponser_matrix)] <- NA

fsponser_matrix <- as.matrix(mat)
upper.tri(fsponser_matrix, diag = TRUE)
diag(fsponser_matrix) <- NA
fsponser_matrix[upper.tri(fsponser_matrix)] <- NA

x <- cbind(which(!is.na(sponser_matrix), arr.ind = TRUE), na.omit(as.vector(sponser_matrix)))
weighteddf <- as.data.frame(x)


sponser_matrixg <- graph.adjacency(sponser_matrix, mode = "undirected", weighted = TRUE)

plot(sponser_matrixg, layout=layout.fruchterman.reingold)
ggplot(weighteddf, aes(x = V3)) +
  geom_histogram()

plot(sponser_matrixg, weights = node_characteristics_final$Weight)

#filtering out connections over 100
fsponser_matrix[fsponser_matrix<25] <- 0
fattempt1 <- graph.adjacency(fsponser_matrix, mode = "undirected", weighted = TRUE)

summary(fattempt1)
E(fattempt1)$weight
plot(fattempt1, layout=layout.fruchterman.reingold)

#internet trying 
###
write.csv(sponser_matrix_full, "matrixfull2.csv")
node_names <- node_characteristics_final %>%
  select(firstLast)
write.csv(node_names, "attributes.csv")
mat1=read.csv("matrixfull2.csv",header=TRUE,row.names=1,check.names=FALSE)
###
sponsermatrix_full2 <- as.matrix(mat1)

order1 <- c("Tammy Baldwin","Dianne Feinstein","Sheldon Whitehouse","Elizabeth Warren","Bill Nelson","Claire McCaskill","Thomas Carper","Jon Tester","Brian Schatz","Tammy Duckworth","Chris Van Hollen"," Joe Manchin", "Michael Bennet","Richard Blumenthal","Edward Markey","Christopher Murphy","Kirsten Gillibrand","Robert Menendez","Debbie Stabenow","Ron Wyden","Jeanne Shaheen","Patrick Leahy","Maria Cantwell","Benjamin Cardin","Jeff Merkley","Tom Udall","Al Franken","Christopher Coons","Tim Kaine","Cory Booker","Kamala Harris","Martin Heinrich","Gary Peters","Sherrod Brown","Robert Casey","Richard Durbin","Amy Klobuchar","Patty Murray","Heidi Heitkamp","Tina Smith","Charles Schumer","Mazie Hirono","Jack Reed","Joe Donnelly","Catherine Cortez Masto","Doug Jones","Mark Warner","Maggie Hassan","Bernard Sanders","Angus King","John Thune","Jerry Moran","Johnny Isakson","James Inhofe","James Lankford","David Perdue","Dean Heller","John Boozman","Shelley Capito","Roy Blunt","John Barrasso","Chuck Grassley","James Risch","Cory Gardner","Tim Scott","Todd Young","Rand Paul","Mike Lee","Marco Rubio","Rob Portman","Steve Daines","John Cornyn","Orrin Hatch","Pat Toomey","Ron Johnson","Tom Cotton","Ted Cruz","John McCain","Michael Enzi","Joni Ernst","Ben Sasse","Thom Tillis","Richard Burr","Bill Cassidy","Jeff Flake","Mike Crapo","Pat Roberts","Roger Wicker","Deb Fischer","Mike Rounds","Dan Sullivan","John Kennedy","Luther Strange","Cindy Hyde-Smith","Susan Collins","Jeff Sessions","Thad Cochran","Lisa Murkowski","Mitch McConnell","Richard Shelby","Lindsey Graham","Lamar Alexander","Bob Corker","John Hoeven","Jon Kyl")

sponsermatrix_full2[,as.character(order1)]

#sponsermatrix_full2[sponsermatrix_full2>100] <- 0
fattempt2 <- graph.adjacency(sponsermatrix_full2, mode="undirected", weighted = TRUE, diag=FALSE)
#looking at the graph attributes
summary(fattempt2)
#looking at the weights
E(fattempt2)$weight

plot.igraph(fattempt2,layout=layout.fruchterman.reingold, edge.color="black",edge.width=E(fattempt2)$weight) #hmm

#node characteristics
V(fattempt2)$Gender=as.character(node_characteristics_final$Gender[match(V(fattempt2)$name, node_characteristics_final$firstLast)]) #for this to work, we need to name the rows and columns of our matrix. i think i can do that. see above

V(fattempt2)$Gender

#V(fattempt2)$color= V(fattempt2)$Gender
#V(fattempt2)$color=gsub("F","red",V(fattempt2)$color)
#V(fattempt2)$color=gsub("M","blue",V(fattempt2)$color)

#plot.igraph(fattempt2,vertex.label=NA,layout=layout.fruchterman.reingold, edge.color="black",edge.width=E(fattempt2)$weight)


V(fattempt2)$Party=as.character(node_characteristics_final$Party[match(V(fattempt2)$name, node_characteristics_final$firstLast)])

V(fattempt2)$color= V(fattempt2)$Party
V(fattempt2)$color=gsub("Democratic","Blue",V(fattempt2)$color)
V(fattempt2)$color=gsub("Republican","Red",V(fattempt2)$color)
V(fattempt2)$color=gsub("Independent","Yellow",V(fattempt2)$color)

#hist(E(fattempt2)$weight ) 


V(fattempt2)$label=V(fattempt2)

plot(fattempt2, vertex.label.cex=.70, vertex.size = 10, layout= layout_in_circle, edge.width= (E(fattempt2)$weight>100), vertex.color = V(fattempt2)$color)

plot(fattempt2)

#graph sample
net1 <- network(sponser_matrix_full, vertex.attr = node_characteristics_final,
                    vertex.attrnames = colnames(node_characteristics_final), directed = F)

igraphnet <- asIgraph(net1)
 

vertex_attr(igraphnet)
plot(igraphnet, vertex.color = ifelse(V(igraphnet)$Gender == "F", "pink", "blue"))

histogram(node_characteristics_final$Weight)
```
```{r}
#new try
top25 <- node_characteristics_final %>%
  mutate(bills = as.numeric("Number of bills cosponsered") + as.numeric("Number of bills sponsered")) %>%
  arrange(desc(bills)) %>%
  top_n(25, bills)
```

```{r}
#743
#92
#70
set.seed(743)
summary(fattempt2)

sampled <- sample.int(vcount(fattempt2), 25)


## pull samples to plot random sampled 
samplegraph <- subgraph(fattempt2, sampled)

V(fattempt2)$Party=as.character(node_characteristics_final$Party[match(V(fattempt2)$name, node_characteristics_final$firstLast)])

V(fattempt2)$color= V(fattempt2)$Party
V(fattempt2)$color=gsub("Democratic","Blue",V(fattempt2)$color)
V(fattempt2)$color=gsub("Republican","Red",V(fattempt2)$color)
V(fattempt2)$color=gsub("Independent","Yellow",V(fattempt2)$color)
V(fattempt2)$label=V(fattempt2)

plot(samplegraph, vertex.label.cex=.75, vertex.size = 10)
```


```{r SBM}
## generation of one SBM network
npc <- 20 # nodes per class
Q <- 5 # classes
n <- npc * Q # nodes
Z<-diag(Q)%x%matrix(1,npc,1)
P<-matrix(runif(Q*Q),Q,Q)
M<-1*(matrix(runif(n*n),n,n)<Z%*%P%*%t(Z)) ## adjacency matrix

my_model <- BM_bernoulli("SBM",M )
my_model$estimate()
which.max(my_model$ICL)
num.clusters<-3
my_model$memberships[[num.clusters]]$Z #gives probability of being in each group
my_model$memberships[[num.clusters]]$plot() #plots the group memberships

sbm_attempt <- BM_bernoulli("SBM", sponser_matrix_full)
sbm_attempt2 <- BM_poisson(
    "SBM",
    sponser_matrix_full,
    verbosity=4,
    autosave='',
    plotting=character(0),
    exploration_factor=1.5,
    explore_min=2,
    explore_max=20,
    ncores=detectCores())
sbm_attempt2$estimate()
which.max(sbm_attempt2$ICL)
num.clusters<-14

output_sbm <- sbm_attempt2$memberships[[num.clusters]]$Z #gives probability of being in each group
sbm_attempt2$memberships[[num.clusters]]$plot() #plots the group memberships


sbm_attempt2$PL
sbm_attempt2$memberships

output_sbm_max <- cbind(apply(output_sbm, 1, max), max.col(output_sbm))
output_sbm_max <- cbind(output_sbm_max, node_characteristics_final$firstLast)
output_sbm_max <- cbind(output_sbm_max, node_characteristics_final$Party)
output_sbm_max <- cbind(output_sbm_max, node_characteristics_final$State)
sbm_output.df <- as.data.frame(output_sbm_max)
sbm_output.df <- setNames(sbm_output.df, c("probability", "class", "name", "party", "state")) %>%
  mutate(class = as.numeric(class)) %>%
  group_by(class) %>% 
  arrange(class)


sbm_attempt2
```

```{r, message = FALSE, warning = FALSE, ERGM}
library(ergm)
library(intergraph)
## how does the weighted nature of the matrix impact how we interpret the model? probably easier with binary indicators. 
## do men cosponsor more bills overall? Adjust for nodes being male, white, old, etc.

ergm_mat <- as.matrix((as.data.frame(sponser_matrix_full)>0) + 0)

# ergm_igraph <- graph_from_adjacency_matrix(ergm_mat, mode = "undirected", weighted = NULL, add.colnames = TRUE, add.rownames = TRUE)

ergm_net <- network(ergm_mat, vertex.attr = node_characteristics_final,
                    vertex.attrnames = colnames(node_characteristics_final), directed = F)

igraph_ob <- asIgraph(ergm_net)

vertex_attr(igraph_ob)
plot(igraph_ob, vertex.color = ifelse(V(igraph_ob)$Gender == "F", "pink", "blue"))

set.seed(3)

x <- sample(1:vcount(igraph_ob), 50)
y <- sample(1:vcount(igraph_ob), 20)
z <- sample(1:vcount(igraph_ob), 20)

## pull samples to run ergm on
samp1 <- subgraph(igraph_ob, which(V(igraph_ob) %in% x))
samp1_network <- asNetwork(samp1)
samp1_ergm <- ergm(samp1_network~ nodefactor("Gender") + nodefactor("Race") + nodematch("Gender") + nodematch("Race") + absdiff("Age") + nodemix("Party") + nodecov("Age") + gwesp(0, fixed = TRUE))
summary(samp1_ergm)

subgraph_function <- function(sub_arg){
  gen_plot <- induced.subgraph(igraph_ob, sub_arg) 
  plot(gen_plot, vertex.color = ifelse(V(igraph_ob)$Gender[sub_arg] == "F", "purple", "yellow"), vertex.label = V(igraph_ob)$Gender[sub_arg])
}


subgraph_function(x)
subgraph_function(y)
subgraph_function(z)

in_vert <- delete.vertices(ergm_net, V(asIgraph(ergm_net))[degree(ergm_net)>100])
plot(in_vert)

in_vert <- 
as_adjacency_matrix(asIgraph(in_vert))

# plot(gen_plot, vertex.color = ifelse(V(igraph_ob)$Gender[y] == "F", "purple", "yellow"), vertex.label = V(igraph_ob)$Gender[])

sponsor_base <- ergm(ergm_net ~ edges)
plot(simulate(sponsor_base))
plot(ergm_net)

sponsor_complex <- ergm(ergm_net~ nodefactor("Gender") + nodefactor("Race") + nodematch("Gender") + nodematch("Race") + absdiff("Age") + nodemix("Party") + nodecov("Age") + gwesp(0, fixed = TRUE))
summary(sponsor_complex)
plot(simulate(sponsor_complex))
complex_gof <- gof(sponsor_complex)
summary(complex_gof)


```